### ISSUE TITLE
Update suggested bibtex to list the work as a NeurIPS paper

### ISSUE THREAD

**Issue by tvercaut** [franciszzj/TP-SIS#2]
The citation currently refers to arxiv only, not NeurIPS:
https://github.com/franciszzj/TP-SIS#citation
This should be modified.

We should also include a cff file:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Comment by franciszzj** [comment]
The citation has been modified and the cff file has been added.
